import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import NabBar from "./navbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Demo App",
  description: "Generated by create demo app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NabBar />

        {children}
      </body>
    </html>
  );
}
