import "./globals.css";
import { Inter } from "next/font/google";
import NabBar from "./navbar";
import ReduxProvider from "./reduxProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Demo App",
  description: "Generated by create demo app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <NabBar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
